version: 1
ATT&CK version: 8.1
creation date: 03/15/2021
name: Cloud App Security Policies
contact: ctid@mitre-engenuity.org
organization: Center for Threat Informed Defense (CTID)
platform: Azure
tags:
  - CASB
  - ''
description: >-
  "Cloud App Security enables you to identify high-risk use and cloud security issues, detect
  abnormal user behavior, and prevent threats in your sanctioned cloud apps. Get visibility into
  user and admin activities and define policies to automatically alert when suspicious behavior or
  specific activities that you consider risky are detected. Draw from the vast amount of Microsoft
  threat intelligence and security research data to help ensure that your sanctioned apps have all
  the security controls you need in place and help you maintain control over them."
techniques:
  - id: T1078
    name: Valid Accounts
    technique-scores:
      - category: Detect
        value: Partial
        comments: >-
          Can identify anomalous behavior such as geographically impossible logins and
          out-of-character activity.
    sub-techniques-scores:
      - sub-techniques:
          - id: T1078.004
            name: Cloud Accounts
          - id: T1078.002
            name: Domain Accounts
          - id: T1078.001
            name: Default Accounts
        scores:
          - category: Detect
            value: Partial
  - id: T1567
    name: Exfiltration Over Web Service
    technique-scores:
      - category: Detect
        value: Partial
        comments: Can identify large volume exfil
    sub-techniques-scores:
      - sub-techniques:
          - id: T1567.002
            name: Exfiltration to Cloud Storage
          - id: T1567.001
            name: Exfiltration to Code Repository
        scores:
          - category: Detect
            value: Partial
            comments: can detect large data exfil events
  - id: T1189
    name: Drive-by Compromise
    technique-scores:
      - category: Detect
        value: Partial
        comments: Can detect outdated client browser
  - id: T1535
    name: Unused/Unsupported Cloud Regions
    technique-scores:
      - category: Detect
        value: Partial
        comments: Can detect unusual region for cloud resource (preview feature as of this writing)
  - id: T1187
    name: Forced Authentication
    technique-scores:
      - category: Detect
        value: Partial
        comments: Can alert on anomalous file sharing
  - id: T1530
    name: Data from Cloud Storage Object
    technique-scores:
      - category: Detect
        value: Partial
        comments: Can detect use of unsanctioned business apps and data exfil to unsanctioned storage apps.
  - id: T1528
    name: Steal Application Access Token
    technique-scores:
      - category: Detect
        value: Partial
        comments: 'Can detect potentially risky apps '
  - id: T1526
    name: Cloud Service Discovery
    technique-scores:
      - category: Detect
        value: Partial
        comments: Can detect anomalous user activity that may be associated with cloud service discovery.
  - id: T1213
    name: Data from Information Repositories
    technique-scores:
      - category: Detect
        value: Partial
        comments: >-
          May detect anomalous user behavior wwrt information repositories such as sharepoint or
          confluence.
    sub-techniques-scores:
      - sub-techniques:
          - id: T1213.002
            name: Sharepoint
          - id: T1213.001
            name: Confluence
        scores:
          - category: Detect
            value: Partial
            comments: May detect anomalous user behavior wrt information repositories.
  - id: T1119
    name: Automated Collection
    technique-scores:
      - category: Protect
        value: Partial
        comments: >-
          Information protection policies can detect and encrypt sensitive information at rest on
          supported platforms.
      - category: Detect
        value: Partial
        comments: Can detect sensitive information at rest.
  - id: T1565
    name: Data Manipulation
    technique-scores:
      - category: Protect
        value: Partial
        comments: >-
          Can detect and encrypt sensitive information at rest on supported platforms, and restrict
          access.
    sub-techniques-scores:
      - sub-techniques:
          - id: T1565.001
            name: Stored Data Manipulation
        scores:
          - category: Protect
            value: Partial
            comments: Can detect and encrypt sensitive information at rest on supported platforms.
  - id: T1133
    name: External Remote Services
    technique-scores:
      - category: Protect
        value: Partial
        comments: Polices of reverse proxy can limit abuse of access from remote devices.
  - id: T1219
    name: Remote Access Software
    technique-scores:
      - category: Protect
        value: Significant
        comments: Can limit potential C2 via unapproved remote access software
  - id: T1484
    name: Domain Policy Modification
    technique-scores:
      - category: Detect
        value: Partial
        comments: Can detect admin activity from risky IP addresses.
    sub-techniques-scores:
      - sub-techniques:
          - id: T1484.002
            name: Domain Trust Modification
          - id: T1484.001
            name: Group Policy Modification
        scores:
          - category: Protect
            value: Partial
            comments: Can detect admin activity from risky IP addresses
  - id: T1098
    name: Account Manipulation
    technique-scores:
      - category: Detect
        value: Partial
        comments: Can detect anomalous admin activity
    sub-techniques-scores:
      - sub-techniques:
          - id: T1098.003
            name: Add Office 365 Global Administrator Role
          - id: T1098.001
            name: Additional Cloud Credentials
          - id: T1098.002
            name: Exchange Email Delegate Permissions
        scores:
          - category: Detect
            value: Partial
            comments: Can detect anomalous admin activity
  - id: T1578
    name: Modify Cloud Compute Infrastructure
    technique-scores:
      - category: Detect
        value: Partial
        comments: Can identify anomalous admin activity
    sub-techniques-scores:
      - sub-techniques:
          - id: T1578.004
            name: Revert Cloud Instance
          - id: T1578.003
            name: Delete Cloud Instance
          - id: T1578.001
            name: Create Snapshot
          - id: T1578.002
            name: Create Cloud Instance
        scores:
          - category: Detect
            value: Partial
            comments: Can identify anomalous admin activity
  - id: T1531
    name: Account Access Removal
    technique-scores:
      - category: Detect
        value: Partial
        comments: Can identify anomalous admin activity
comments: 'This is Azure "CASB" '
references:
  - 'https://docs.microsoft.com/en-us/cloud-app-security/policies-cloud-discovery'
  - 'https://docs.microsoft.com/en-us/cloud-app-security/policies-information-protection'
